// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfngtrpzirrtuxjhqmak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmbmd0cnB6aXJydHV4amhxbWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDczODYsImV4cCI6MjA2NTM4MzM4Nn0.Kgw-Aw_a5XxNaDD-Ij3YGSMAOdG_HkxzSkSNZsbQrn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);